<?php


namespace Codeable\CommissionEnhancer\Controller;


class VendorsImplementation extends \WC_Product_Vendors {

	public function dependencies() {
		require_once( CE_PLUGIN_DIR . 'src/Controller/VendorsCommission.php' );
		return parent::dependencies(); // TODO: Change the autogenerated stub
	}
}